# Generated by Django 6.1.1 on 2026-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(choices=[('city_clinic', 'City Clinic'), ('healthcare_center', 'Healthcare Center'), ('wellness_hub', 'Wellness Hub'), ('family_health', 'Family Health')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
